export const BRANCHES = ['Computer Science', 'Electronics', 'Mechanical', 'Civil', 'IT', 'All Branches'];
export const SECTIONS = ['A', 'B', 'C', 'D', 'All Sections'];
export const YEARS = ['1st Year', '2nd Year', '3rd Year', '4th Year', 'All Years'];
export const CATEGORIES = ['Exam', 'Placement', 'Scholarship', 'Event', 'Academic', 'Club', 'General'];
export const DEPARTMENTS = ['Computer Science', 'Electronics', 'Mechanical', 'Civil', 'IT', 'Administration', 'Placement Cell'];
export const PRIORITIES = ['high', 'medium', 'low'];

export const DEFAULT_NOTICES = [
  {
    id: '1',
    title: 'End Semester Examination Schedule 2026',
    description: 'The end semester examinations for all branches will commence from June 20, 2026. Students must check their individual timetables on the college portal. All students are required to carry their ID cards and admit cards to the examination hall. Mobile phones and electronic devices are strictly prohibited inside the examination hall.',
    category: 'Exam',
    department: 'Administration',
    priority: 'high',
    deadline: '2026-06-20',
    date: '2026-06-01',
    mandatory: true,
    branches: ['All Branches'],
    years: ['All Years'],
    sections: ['All Sections'],
    attachments: [{ name: 'Exam_Schedule.pdf', url: '#' }],
    views: 342,
    eligibility: 'All enrolled students of the current academic year',
    additionalDetails: 'Examination halls will be announced one week prior. Students with backlog subjects must register separately.',
  },
  {
    id: '2',
    title: 'TCS Placement Drive - June 2026',
    description: 'Tata Consultancy Services is conducting a placement drive on campus on June 25, 2026. Eligible students from CS, IT, and Electronics branches with minimum 60% aggregate are invited to register. The selection process includes aptitude test, technical interview, and HR round.',
    category: 'Placement',
    department: 'Placement Cell',
    priority: 'high',
    deadline: '2026-06-25',
    date: '2026-06-03',
    mandatory: false,
    branches: ['Computer Science', 'IT', 'Electronics'],
    years: ['3rd Year', '4th Year'],
    sections: ['All Sections'],
    attachments: [{ name: 'TCS_Registration_Form.pdf', url: '#' }],
    views: 256,
    eligibility: 'CS, IT, Electronics students with 60%+ aggregate, no active backlogs',
    additionalDetails: 'Registration deadline: June 15, 2026. Dress code: Formal.',
  },
  {
    id: '3',
    title: 'Merit Scholarship Application 2026-27',
    description: 'Applications are now open for the Merit Scholarship program for the academic year 2026-27. Students with outstanding academic performance in the previous semester are encouraged to apply. Scholarship amount ranges from ₹25,000 to ₹1,00,000 based on merit ranking.',
    category: 'Scholarship',
    department: 'Administration',
    priority: 'medium',
    deadline: '2026-06-30',
    date: '2026-06-05',
    mandatory: false,
    branches: ['All Branches'],
    years: ['All Years'],
    sections: ['All Sections'],
    attachments: [{ name: 'Scholarship_Form.pdf', url: '#' }],
    views: 189,
    eligibility: 'Students with minimum 75% in previous semester',
    additionalDetails: 'Submit application with income certificate and mark sheets.',
  },
  {
    id: '4',
    title: 'Tech Fest 2026 - Registration Open',
    description: 'The annual Tech Fest will be held from July 10-12, 2026. Events include hackathon, coding competition, robotics challenge, and tech talks by industry leaders. Registration is free for all college students. External participants can register with a fee of ₹500.',
    category: 'Event',
    department: 'Computer Science',
    priority: 'low',
    deadline: '2026-07-10',
    date: '2026-06-07',
    mandatory: false,
    branches: ['All Branches'],
    years: ['All Years'],
    sections: ['All Sections'],
    attachments: [{ name: 'TechFest_Brochure.pdf', url: '#' }],
    views: 412,
    eligibility: 'Open to all students and external participants',
    additionalDetails: 'Team size for hackathon: 2-4 members. Prizes worth ₹2 Lakhs.',
  },
  {
    id: '5',
    title: 'Mid-Semester Project Submission Deadline',
    description: 'All students enrolled in project courses must submit their mid-semester progress reports and demo videos by the specified deadline. Late submissions will incur a penalty of 10% per day. Reports must follow the prescribed format available on the department website.',
    category: 'Academic',
    department: 'Computer Science',
    priority: 'high',
    deadline: '2026-06-15',
    date: '2026-06-02',
    mandatory: true,
    branches: ['Computer Science', 'IT'],
    years: ['3rd Year', '4th Year'],
    sections: ['All Sections'],
    attachments: [{ name: 'Project_Report_Format.pdf', url: '#' }],
    views: 178,
    eligibility: '3rd and 4th year CS/IT students enrolled in project courses',
    additionalDetails: 'Submit via the online portal. Demo video max 10 minutes.',
  },
  {
    id: '6',
    title: 'Coding Club Weekly Meetup',
    description: 'The Coding Club invites all programming enthusiasts to its weekly meetup this Saturday. Topic: Introduction to Machine Learning with Python. Hands-on session with Jupyter notebooks. Snacks will be provided.',
    category: 'Club',
    department: 'Computer Science',
    priority: 'low',
    deadline: '2026-06-14',
    date: '2026-06-08',
    mandatory: false,
    branches: ['All Branches'],
    years: ['All Years'],
    sections: ['All Sections'],
    attachments: [],
    views: 95,
    eligibility: 'Open to all interested students',
    additionalDetails: 'Venue: CS Lab 3, Time: 4:00 PM - 6:00 PM',
  },
];

export const ANALYTICS_DATA = {
  noticeViews: [
    { label: 'Mon', value: 120 },
    { label: 'Tue', value: 185 },
    { label: 'Wed', value: 210 },
    { label: 'Thu', value: 165 },
    { label: 'Fri', value: 240 },
    { label: 'Sat', value: 95 },
    { label: 'Sun', value: 60 },
  ],
  studentEngagement: [
    { label: 'Week 1', value: 65 },
    { label: 'Week 2', value: 72 },
    { label: 'Week 3', value: 78 },
    { label: 'Week 4', value: 85 },
  ],
  departmentReach: [
    { label: 'CS', value: 340 },
    { label: 'IT', value: 280 },
    { label: 'ECE', value: 220 },
    { label: 'ME', value: 180 },
    { label: 'CE', value: 150 },
  ],
  faqAnalytics: [
    { label: 'Exams', value: 45 },
    { label: 'Placement', value: 38 },
    { label: 'Scholarship', value: 25 },
    { label: 'Events', value: 18 },
    { label: 'Other', value: 12 },
  ],
  monthlyActivity: [
    { label: 'Jan', value: 420 },
    { label: 'Feb', value: 380 },
    { label: 'Mar', value: 510 },
    { label: 'Apr', value: 460 },
    { label: 'May', value: 590 },
    { label: 'Jun', value: 680 },
  ],
};

export const CHATBOT_RESPONSES = {
  exams: 'The end semester examinations begin on June 20, 2026. Check the notice "End Semester Examination Schedule 2026" for detailed timetables. Mid-semester project submissions are due June 15.',
  scholarship: 'The Merit Scholarship Application for 2026-27 is open until June 30, 2026. You need minimum 75% in the previous semester. Download the form from the Scholarship notice.',
  placement: 'TCS Placement Drive is scheduled for June 25, 2026. Registration deadline is June 15. Eligible branches: CS, IT, Electronics with 60%+ aggregate.',
  default: 'I can help you find notices about exams, placements, scholarships, and events. Try asking about upcoming exams, scholarship forms, or placement drive dates!',
};

export const ADMIN_CREDENTIALS = {
  email: 'admin@college.edu',
  password: 'admin123',
};
